### ISSUE TITLE
OverlayGauge::gauge_texture_ never deleted?

### ISSUE THREAD

**Issue by JDeeth** [PhilippMuenzel/PPL#9]
https://github.com/PhilippMuenzel/PPL/blob/793713391bd616e1ef91c7a8a3345abdbe522be5/src/overlaygauge.cpp#L105

Should there be a corresponding call to glDeleteTexture in the destructor?

**Comment by PhilippMuenzel** [comment]
glDeleteTextures does not correspond to glTexImage2D but rather to glGenTextures instead. glGenTextures is never called by us, but by X-Plane, and we have borrowed the texture ID from X-Plane, not from OpenGL itself, by calling XPLMGenerateTextureNumbers. So X-Plane deletes those, not us.
